/**
 * Curated word list for AAC (Augmentative and Alternative Communication)
 * Target audience: 8-year-olds and younger children
 *
 * Sources:
 * - Dolch Sight Words (Pre-primer through 3rd Grade)
 * - Frye High-Frequency Words
 * - Common AAC Core Vocabulary
 * - ARASAAC frequency lists
 *
 * Categories prioritized:
 * - High-frequency core verbs
 * - School-related terms
 * - Emotions and feelings
 * - Common animals
 * - Foods and drinks
 * - Family and people
 * - Places
 * - Basic needs/responses
 * - Colors, numbers, time
 * - Body parts
 * - Clothing
 * - Weather
 * - Transportation
 */

export interface WordEntry {
  word: string;
  category: string;
  priority: number; // 1 = highest priority (Dolch/core), 2 = high, 3 = medium
}

// Core verbs - essential for communication
const CORE_VERBS: WordEntry[] = [
  // Dolch verbs
  { word: "go", category: "Actions", priority: 1 },
  { word: "come", category: "Actions", priority: 1 },
  { word: "want", category: "Actions", priority: 1 },
  { word: "like", category: "Actions", priority: 1 },
  { word: "see", category: "Actions", priority: 1 },
  { word: "look", category: "Actions", priority: 1 },
  { word: "get", category: "Actions", priority: 1 },
  { word: "give", category: "Actions", priority: 1 },
  { word: "take", category: "Actions", priority: 1 },
  { word: "put", category: "Actions", priority: 1 },
  { word: "make", category: "Actions", priority: 1 },
  { word: "do", category: "Actions", priority: 1 },
  { word: "have", category: "Actions", priority: 1 },
  { word: "say", category: "Actions", priority: 1 },
  { word: "tell", category: "Actions", priority: 1 },
  { word: "ask", category: "Actions", priority: 1 },
  { word: "help", category: "Actions", priority: 1 },
  { word: "stop", category: "Actions", priority: 1 },
  { word: "start", category: "Actions", priority: 1 },
  { word: "open", category: "Actions", priority: 1 },
  { word: "close", category: "Actions", priority: 1 },
  { word: "run", category: "Actions", priority: 1 },
  { word: "jump", category: "Actions", priority: 1 },
  { word: "sit", category: "Actions", priority: 1 },
  { word: "stand", category: "Actions", priority: 1 },
  { word: "walk", category: "Actions", priority: 1 },
  { word: "eat", category: "Actions", priority: 1 },
  { word: "drink", category: "Actions", priority: 1 },
  { word: "sleep", category: "Actions", priority: 1 },
  { word: "play", category: "Actions", priority: 1 },
  { word: "read", category: "Actions", priority: 1 },
  { word: "write", category: "Actions", priority: 1 },
  { word: "draw", category: "Actions", priority: 1 },
  { word: "color", category: "Actions", priority: 1 },
  { word: "cut", category: "Actions", priority: 1 },
  { word: "clean", category: "Actions", priority: 1 },
  { word: "wash", category: "Actions", priority: 1 },
  { word: "brush", category: "Actions", priority: 1 },
  { word: "listen", category: "Actions", priority: 1 },
  { word: "think", category: "Actions", priority: 1 },
  { word: "know", category: "Actions", priority: 1 },
  { word: "find", category: "Actions", priority: 1 },
  { word: "show", category: "Actions", priority: 1 },
  { word: "try", category: "Actions", priority: 1 },
  { word: "use", category: "Actions", priority: 1 },
  { word: "hold", category: "Actions", priority: 1 },
  { word: "carry", category: "Actions", priority: 1 },
  { word: "bring", category: "Actions", priority: 1 },
  { word: "turn", category: "Actions", priority: 1 },
  { word: "move", category: "Actions", priority: 1 },
  { word: "push", category: "Actions", priority: 1 },
  { word: "pull", category: "Actions", priority: 1 },
  { word: "throw", category: "Actions", priority: 1 },
  { word: "catch", category: "Actions", priority: 1 },
  { word: "kick", category: "Actions", priority: 1 },
  { word: "climb", category: "Actions", priority: 2 },
  { word: "swing", category: "Actions", priority: 2 },
  { word: "slide", category: "Actions", priority: 2 },
  { word: "ride", category: "Actions", priority: 2 },
  { word: "drive", category: "Actions", priority: 2 },
  { word: "fly", category: "Actions", priority: 2 },
  { word: "swim", category: "Actions", priority: 2 },
  { word: "dance", category: "Actions", priority: 2 },
  { word: "sing", category: "Actions", priority: 2 },
  { word: "clap", category: "Actions", priority: 2 },
  { word: "wave", category: "Actions", priority: 2 },
  { word: "hug", category: "Actions", priority: 2 },
  { word: "kiss", category: "Actions", priority: 2 },
  { word: "share", category: "Actions", priority: 2 },
  { word: "wait", category: "Actions", priority: 1 },
  { word: "finish", category: "Actions", priority: 1 },
  { word: "begin", category: "Actions", priority: 2 },
  { word: "work", category: "Actions", priority: 2 },
  { word: "learn", category: "Actions", priority: 2 },
  { word: "teach", category: "Actions", priority: 2 },
  { word: "build", category: "Actions", priority: 2 },
  { word: "break", category: "Actions", priority: 2 },
  { word: "fix", category: "Actions", priority: 2 },
  { word: "cook", category: "Actions", priority: 2 },
  { word: "bake", category: "Actions", priority: 2 },
  { word: "pour", category: "Actions", priority: 2 },
  { word: "mix", category: "Actions", priority: 2 },
  { word: "stir", category: "Actions", priority: 3 },
  { word: "taste", category: "Actions", priority: 2 },
  { word: "smell", category: "Actions", priority: 2 },
  { word: "touch", category: "Actions", priority: 2 },
  { word: "feel", category: "Actions", priority: 2 },
  { word: "hear", category: "Actions", priority: 2 },
  { word: "call", category: "Actions", priority: 2 },
  { word: "answer", category: "Actions", priority: 2 },
  { word: "point", category: "Actions", priority: 2 },
  { word: "pick", category: "Actions", priority: 2 },
  { word: "choose", category: "Actions", priority: 2 },
  { word: "count", category: "Actions", priority: 2 },
  { word: "measure", category: "Actions", priority: 3 },
  { word: "grow", category: "Actions", priority: 2 },
  { word: "change", category: "Actions", priority: 2 },
  { word: "hide", category: "Actions", priority: 2 },
  { word: "seek", category: "Actions", priority: 3 },
  { word: "pretend", category: "Actions", priority: 2 },
  { word: "imagine", category: "Actions", priority: 3 },
  { word: "remember", category: "Actions", priority: 2 },
  { word: "forget", category: "Actions", priority: 2 },
  { word: "wake", category: "Actions", priority: 2 },
  { word: "dress", category: "Actions", priority: 2 },
  { word: "brush teeth", category: "Actions", priority: 2 },
  { word: "comb", category: "Actions", priority: 3 },
  { word: "tie", category: "Actions", priority: 3 },
  { word: "zip", category: "Actions", priority: 3 },
  { word: "button", category: "Actions", priority: 3 },
  { word: "fold", category: "Actions", priority: 3 },
  { word: "blow", category: "Actions", priority: 2 },
  { word: "bite", category: "Actions", priority: 2 },
  { word: "chew", category: "Actions", priority: 2 },
  { word: "swallow", category: "Actions", priority: 3 },
  { word: "laugh", category: "Actions", priority: 2 },
  { word: "cry", category: "Actions", priority: 2 },
  { word: "smile", category: "Actions", priority: 2 },
  { word: "frown", category: "Actions", priority: 3 },
  { word: "yell", category: "Actions", priority: 2 },
  { word: "whisper", category: "Actions", priority: 3 },
  { word: "talk", category: "Actions", priority: 1 },
  { word: "speak", category: "Actions", priority: 2 },
];

// Emotions and feelings
const EMOTIONS: WordEntry[] = [
  { word: "happy", category: "Feelings", priority: 1 },
  { word: "sad", category: "Feelings", priority: 1 },
  { word: "angry", category: "Feelings", priority: 1 },
  { word: "scared", category: "Feelings", priority: 1 },
  { word: "afraid", category: "Feelings", priority: 2 },
  { word: "worried", category: "Feelings", priority: 2 },
  { word: "nervous", category: "Feelings", priority: 2 },
  { word: "excited", category: "Feelings", priority: 1 },
  { word: "surprised", category: "Feelings", priority: 2 },
  { word: "confused", category: "Feelings", priority: 2 },
  { word: "frustrated", category: "Feelings", priority: 2 },
  { word: "tired", category: "Feelings", priority: 1 },
  { word: "sleepy", category: "Feelings", priority: 2 },
  { word: "hungry", category: "Feelings", priority: 1 },
  { word: "thirsty", category: "Feelings", priority: 1 },
  { word: "sick", category: "Feelings", priority: 1 },
  { word: "hurt", category: "Feelings", priority: 1 },
  { word: "pain", category: "Feelings", priority: 2 },
  { word: "better", category: "Feelings", priority: 2 },
  { word: "good", category: "Feelings", priority: 1 },
  { word: "bad", category: "Feelings", priority: 1 },
  { word: "okay", category: "Feelings", priority: 1 },
  { word: "fine", category: "Feelings", priority: 2 },
  { word: "bored", category: "Feelings", priority: 2 },
  { word: "lonely", category: "Feelings", priority: 2 },
  { word: "proud", category: "Feelings", priority: 2 },
  { word: "shy", category: "Feelings", priority: 2 },
  { word: "embarrassed", category: "Feelings", priority: 3 },
  { word: "jealous", category: "Feelings", priority: 3 },
  { word: "calm", category: "Feelings", priority: 2 },
  { word: "peaceful", category: "Feelings", priority: 3 },
  { word: "silly", category: "Feelings", priority: 2 },
  { word: "funny", category: "Feelings", priority: 2 },
  { word: "crazy", category: "Feelings", priority: 3 },
  { word: "loving", category: "Feelings", priority: 2 },
  { word: "kind", category: "Feelings", priority: 2 },
  { word: "mean", category: "Feelings", priority: 2 },
  { word: "brave", category: "Feelings", priority: 2 },
  { word: "strong", category: "Feelings", priority: 2 },
  { word: "weak", category: "Feelings", priority: 3 },
  { word: "hot", category: "Feelings", priority: 1 },
  { word: "cold", category: "Feelings", priority: 1 },
  { word: "comfortable", category: "Feelings", priority: 3 },
  { word: "uncomfortable", category: "Feelings", priority: 3 },
];

// Family and people
const PEOPLE: WordEntry[] = [
  { word: "mom", category: "People", priority: 1 },
  { word: "mommy", category: "People", priority: 1 },
  { word: "mother", category: "People", priority: 2 },
  { word: "dad", category: "People", priority: 1 },
  { word: "daddy", category: "People", priority: 1 },
  { word: "father", category: "People", priority: 2 },
  { word: "brother", category: "People", priority: 1 },
  { word: "sister", category: "People", priority: 1 },
  { word: "baby", category: "People", priority: 1 },
  { word: "grandma", category: "People", priority: 1 },
  { word: "grandmother", category: "People", priority: 2 },
  { word: "grandpa", category: "People", priority: 1 },
  { word: "grandfather", category: "People", priority: 2 },
  { word: "family", category: "People", priority: 1 },
  { word: "friend", category: "People", priority: 1 },
  { word: "boy", category: "People", priority: 1 },
  { word: "girl", category: "People", priority: 1 },
  { word: "man", category: "People", priority: 1 },
  { word: "woman", category: "People", priority: 1 },
  { word: "child", category: "People", priority: 2 },
  { word: "children", category: "People", priority: 2 },
  { word: "kid", category: "People", priority: 2 },
  { word: "people", category: "People", priority: 2 },
  { word: "person", category: "People", priority: 2 },
  { word: "teacher", category: "People", priority: 1 },
  { word: "student", category: "People", priority: 2 },
  { word: "doctor", category: "People", priority: 1 },
  { word: "nurse", category: "People", priority: 2 },
  { word: "dentist", category: "People", priority: 2 },
  { word: "firefighter", category: "People", priority: 2 },
  { word: "police officer", category: "People", priority: 2 },
  { word: "mail carrier", category: "People", priority: 3 },
  { word: "bus driver", category: "People", priority: 2 },
  { word: "chef", category: "People", priority: 3 },
  { word: "farmer", category: "People", priority: 2 },
  { word: "veterinarian", category: "People", priority: 3 },
  { word: "librarian", category: "People", priority: 3 },
  { word: "principal", category: "People", priority: 2 },
  { word: "coach", category: "People", priority: 2 },
  { word: "neighbor", category: "People", priority: 3 },
  { word: "aunt", category: "People", priority: 2 },
  { word: "uncle", category: "People", priority: 2 },
  { word: "cousin", category: "People", priority: 2 },
  { word: "pet", category: "People", priority: 2 },
];

// Animals
const ANIMALS: WordEntry[] = [
  { word: "dog", category: "Animals", priority: 1 },
  { word: "puppy", category: "Animals", priority: 1 },
  { word: "cat", category: "Animals", priority: 1 },
  { word: "kitten", category: "Animals", priority: 2 },
  { word: "bird", category: "Animals", priority: 1 },
  { word: "fish", category: "Animals", priority: 1 },
  { word: "rabbit", category: "Animals", priority: 1 },
  { word: "bunny", category: "Animals", priority: 1 },
  { word: "hamster", category: "Animals", priority: 2 },
  { word: "guinea pig", category: "Animals", priority: 3 },
  { word: "horse", category: "Animals", priority: 1 },
  { word: "pony", category: "Animals", priority: 2 },
  { word: "cow", category: "Animals", priority: 1 },
  { word: "pig", category: "Animals", priority: 1 },
  { word: "sheep", category: "Animals", priority: 2 },
  { word: "goat", category: "Animals", priority: 2 },
  { word: "chicken", category: "Animals", priority: 1 },
  { word: "duck", category: "Animals", priority: 1 },
  { word: "turkey", category: "Animals", priority: 2 },
  { word: "rooster", category: "Animals", priority: 3 },
  { word: "lion", category: "Animals", priority: 1 },
  { word: "tiger", category: "Animals", priority: 1 },
  { word: "bear", category: "Animals", priority: 1 },
  { word: "elephant", category: "Animals", priority: 1 },
  { word: "giraffe", category: "Animals", priority: 1 },
  { word: "zebra", category: "Animals", priority: 2 },
  { word: "monkey", category: "Animals", priority: 1 },
  { word: "gorilla", category: "Animals", priority: 2 },
  { word: "hippo", category: "Animals", priority: 2 },
  { word: "rhino", category: "Animals", priority: 3 },
  { word: "kangaroo", category: "Animals", priority: 2 },
  { word: "koala", category: "Animals", priority: 2 },
  { word: "panda", category: "Animals", priority: 2 },
  { word: "wolf", category: "Animals", priority: 2 },
  { word: "fox", category: "Animals", priority: 2 },
  { word: "deer", category: "Animals", priority: 2 },
  { word: "moose", category: "Animals", priority: 3 },
  { word: "squirrel", category: "Animals", priority: 2 },
  { word: "mouse", category: "Animals", priority: 1 },
  { word: "rat", category: "Animals", priority: 3 },
  { word: "frog", category: "Animals", priority: 1 },
  { word: "toad", category: "Animals", priority: 3 },
  { word: "snake", category: "Animals", priority: 2 },
  { word: "turtle", category: "Animals", priority: 1 },
  { word: "lizard", category: "Animals", priority: 2 },
  { word: "alligator", category: "Animals", priority: 2 },
  { word: "crocodile", category: "Animals", priority: 2 },
  { word: "dinosaur", category: "Animals", priority: 1 },
  { word: "shark", category: "Animals", priority: 2 },
  { word: "whale", category: "Animals", priority: 2 },
  { word: "dolphin", category: "Animals", priority: 2 },
  { word: "octopus", category: "Animals", priority: 2 },
  { word: "jellyfish", category: "Animals", priority: 3 },
  { word: "crab", category: "Animals", priority: 2 },
  { word: "lobster", category: "Animals", priority: 3 },
  { word: "starfish", category: "Animals", priority: 2 },
  { word: "seahorse", category: "Animals", priority: 3 },
  { word: "butterfly", category: "Animals", priority: 1 },
  { word: "bee", category: "Animals", priority: 2 },
  { word: "ladybug", category: "Animals", priority: 2 },
  { word: "spider", category: "Animals", priority: 2 },
  { word: "ant", category: "Animals", priority: 2 },
  { word: "caterpillar", category: "Animals", priority: 2 },
  { word: "dragonfly", category: "Animals", priority: 3 },
  { word: "grasshopper", category: "Animals", priority: 3 },
  { word: "snail", category: "Animals", priority: 2 },
  { word: "worm", category: "Animals", priority: 2 },
  { word: "owl", category: "Animals", priority: 2 },
  { word: "eagle", category: "Animals", priority: 2 },
  { word: "penguin", category: "Animals", priority: 1 },
  { word: "flamingo", category: "Animals", priority: 3 },
  { word: "parrot", category: "Animals", priority: 2 },
  { word: "peacock", category: "Animals", priority: 3 },
  { word: "swan", category: "Animals", priority: 3 },
  { word: "goose", category: "Animals", priority: 3 },
  { word: "bat", category: "Animals", priority: 2 },
  { word: "seal", category: "Animals", priority: 2 },
  { word: "otter", category: "Animals", priority: 3 },
  { word: "beaver", category: "Animals", priority: 3 },
  { word: "skunk", category: "Animals", priority: 3 },
  { word: "raccoon", category: "Animals", priority: 3 },
  { word: "hedgehog", category: "Animals", priority: 3 },
  { word: "camel", category: "Animals", priority: 2 },
  { word: "leopard", category: "Animals", priority: 3 },
  { word: "cheetah", category: "Animals", priority: 3 },
  { word: "jaguar", category: "Animals", priority: 3 },
  { word: "panther", category: "Animals", priority: 3 },
];

// Foods
const FOODS: WordEntry[] = [
  { word: "apple", category: "Food", priority: 1 },
  { word: "banana", category: "Food", priority: 1 },
  { word: "orange", category: "Food", priority: 1 },
  { word: "grapes", category: "Food", priority: 1 },
  { word: "strawberry", category: "Food", priority: 1 },
  { word: "blueberry", category: "Food", priority: 2 },
  { word: "raspberry", category: "Food", priority: 3 },
  { word: "watermelon", category: "Food", priority: 1 },
  { word: "melon", category: "Food", priority: 2 },
  { word: "peach", category: "Food", priority: 2 },
  { word: "pear", category: "Food", priority: 2 },
  { word: "cherry", category: "Food", priority: 2 },
  { word: "lemon", category: "Food", priority: 2 },
  { word: "lime", category: "Food", priority: 3 },
  { word: "pineapple", category: "Food", priority: 2 },
  { word: "mango", category: "Food", priority: 2 },
  { word: "kiwi", category: "Food", priority: 3 },
  { word: "coconut", category: "Food", priority: 3 },
  { word: "carrot", category: "Food", priority: 1 },
  { word: "broccoli", category: "Food", priority: 1 },
  { word: "corn", category: "Food", priority: 1 },
  { word: "peas", category: "Food", priority: 2 },
  { word: "beans", category: "Food", priority: 2 },
  { word: "potato", category: "Food", priority: 1 },
  { word: "tomato", category: "Food", priority: 1 },
  { word: "lettuce", category: "Food", priority: 2 },
  { word: "cucumber", category: "Food", priority: 2 },
  { word: "celery", category: "Food", priority: 3 },
  { word: "onion", category: "Food", priority: 2 },
  { word: "pepper", category: "Food", priority: 2 },
  { word: "mushroom", category: "Food", priority: 2 },
  { word: "spinach", category: "Food", priority: 3 },
  { word: "cauliflower", category: "Food", priority: 3 },
  { word: "cabbage", category: "Food", priority: 3 },
  { word: "bread", category: "Food", priority: 1 },
  { word: "toast", category: "Food", priority: 1 },
  { word: "sandwich", category: "Food", priority: 1 },
  { word: "hamburger", category: "Food", priority: 1 },
  { word: "hot dog", category: "Food", priority: 1 },
  { word: "pizza", category: "Food", priority: 1 },
  { word: "pasta", category: "Food", priority: 1 },
  { word: "spaghetti", category: "Food", priority: 1 },
  { word: "noodles", category: "Food", priority: 2 },
  { word: "rice", category: "Food", priority: 1 },
  { word: "soup", category: "Food", priority: 1 },
  { word: "salad", category: "Food", priority: 2 },
  { word: "taco", category: "Food", priority: 2 },
  { word: "burrito", category: "Food", priority: 3 },
  { word: "chicken", category: "Food", priority: 1 },
  { word: "fish", category: "Food", priority: 1 },
  { word: "meat", category: "Food", priority: 2 },
  { word: "beef", category: "Food", priority: 3 },
  { word: "pork", category: "Food", priority: 3 },
  { word: "bacon", category: "Food", priority: 2 },
  { word: "sausage", category: "Food", priority: 2 },
  { word: "ham", category: "Food", priority: 2 },
  { word: "turkey", category: "Food", priority: 2 },
  { word: "egg", category: "Food", priority: 1 },
  { word: "cheese", category: "Food", priority: 1 },
  { word: "butter", category: "Food", priority: 2 },
  { word: "yogurt", category: "Food", priority: 1 },
  { word: "cereal", category: "Food", priority: 1 },
  { word: "oatmeal", category: "Food", priority: 2 },
  { word: "pancakes", category: "Food", priority: 1 },
  { word: "waffle", category: "Food", priority: 2 },
  { word: "french fries", category: "Food", priority: 1 },
  { word: "chips", category: "Food", priority: 1 },
  { word: "crackers", category: "Food", priority: 2 },
  { word: "popcorn", category: "Food", priority: 2 },
  { word: "pretzel", category: "Food", priority: 3 },
  { word: "nuts", category: "Food", priority: 2 },
  { word: "peanut butter", category: "Food", priority: 1 },
  { word: "jelly", category: "Food", priority: 2 },
  { word: "jam", category: "Food", priority: 3 },
  { word: "honey", category: "Food", priority: 2 },
  { word: "sugar", category: "Food", priority: 2 },
  { word: "salt", category: "Food", priority: 2 },
  { word: "ketchup", category: "Food", priority: 2 },
  { word: "mustard", category: "Food", priority: 3 },
  { word: "mayonnaise", category: "Food", priority: 3 },
  { word: "cookie", category: "Food", priority: 1 },
  { word: "cake", category: "Food", priority: 1 },
  { word: "cupcake", category: "Food", priority: 2 },
  { word: "pie", category: "Food", priority: 2 },
  { word: "donut", category: "Food", priority: 2 },
  { word: "muffin", category: "Food", priority: 2 },
  { word: "brownie", category: "Food", priority: 3 },
  { word: "candy", category: "Food", priority: 1 },
  { word: "chocolate", category: "Food", priority: 1 },
  { word: "ice cream", category: "Food", priority: 1 },
  { word: "popsicle", category: "Food", priority: 2 },
  { word: "pudding", category: "Food", priority: 3 },
  { word: "gummy bears", category: "Food", priority: 3 },
  { word: "lollipop", category: "Food", priority: 2 },
  { word: "fruit snacks", category: "Food", priority: 2 },
  { word: "granola bar", category: "Food", priority: 3 },
  { word: "applesauce", category: "Food", priority: 2 },
  { word: "macaroni and cheese", category: "Food", priority: 1 },
  { word: "chicken nuggets", category: "Food", priority: 1 },
  { word: "fish sticks", category: "Food", priority: 2 },
  { word: "grilled cheese", category: "Food", priority: 2 },
];

// Drinks
const DRINKS: WordEntry[] = [
  { word: "water", category: "Drinks", priority: 1 },
  { word: "milk", category: "Drinks", priority: 1 },
  { word: "juice", category: "Drinks", priority: 1 },
  { word: "apple juice", category: "Drinks", priority: 1 },
  { word: "orange juice", category: "Drinks", priority: 1 },
  { word: "grape juice", category: "Drinks", priority: 2 },
  { word: "lemonade", category: "Drinks", priority: 1 },
  { word: "soda", category: "Drinks", priority: 2 },
  { word: "hot chocolate", category: "Drinks", priority: 1 },
  { word: "tea", category: "Drinks", priority: 2 },
  { word: "coffee", category: "Drinks", priority: 3 },
  { word: "milkshake", category: "Drinks", priority: 1 },
  { word: "smoothie", category: "Drinks", priority: 2 },
  { word: "chocolate milk", category: "Drinks", priority: 1 },
  { word: "strawberry milk", category: "Drinks", priority: 2 },
];

// Places
const PLACES: WordEntry[] = [
  { word: "home", category: "Places", priority: 1 },
  { word: "house", category: "Places", priority: 1 },
  { word: "school", category: "Places", priority: 1 },
  { word: "classroom", category: "Places", priority: 1 },
  { word: "playground", category: "Places", priority: 1 },
  { word: "park", category: "Places", priority: 1 },
  { word: "store", category: "Places", priority: 1 },
  { word: "grocery store", category: "Places", priority: 2 },
  { word: "supermarket", category: "Places", priority: 3 },
  { word: "mall", category: "Places", priority: 2 },
  { word: "restaurant", category: "Places", priority: 1 },
  { word: "hospital", category: "Places", priority: 2 },
  { word: "doctor office", category: "Places", priority: 2 },
  { word: "dentist office", category: "Places", priority: 3 },
  { word: "library", category: "Places", priority: 1 },
  { word: "church", category: "Places", priority: 2 },
  { word: "beach", category: "Places", priority: 1 },
  { word: "pool", category: "Places", priority: 1 },
  { word: "swimming pool", category: "Places", priority: 2 },
  { word: "zoo", category: "Places", priority: 1 },
  { word: "aquarium", category: "Places", priority: 2 },
  { word: "museum", category: "Places", priority: 2 },
  { word: "movie theater", category: "Places", priority: 2 },
  { word: "farm", category: "Places", priority: 1 },
  { word: "forest", category: "Places", priority: 2 },
  { word: "jungle", category: "Places", priority: 2 },
  { word: "mountain", category: "Places", priority: 2 },
  { word: "lake", category: "Places", priority: 2 },
  { word: "river", category: "Places", priority: 2 },
  { word: "ocean", category: "Places", priority: 2 },
  { word: "city", category: "Places", priority: 2 },
  { word: "town", category: "Places", priority: 3 },
  { word: "country", category: "Places", priority: 3 },
  { word: "airport", category: "Places", priority: 2 },
  { word: "train station", category: "Places", priority: 3 },
  { word: "bus stop", category: "Places", priority: 2 },
  { word: "gas station", category: "Places", priority: 3 },
  { word: "fire station", category: "Places", priority: 2 },
  { word: "police station", category: "Places", priority: 3 },
  { word: "post office", category: "Places", priority: 3 },
  { word: "bank", category: "Places", priority: 3 },
  // Rooms
  { word: "bedroom", category: "Places", priority: 1 },
  { word: "bathroom", category: "Places", priority: 1 },
  { word: "kitchen", category: "Places", priority: 1 },
  { word: "living room", category: "Places", priority: 1 },
  { word: "dining room", category: "Places", priority: 2 },
  { word: "garage", category: "Places", priority: 2 },
  { word: "basement", category: "Places", priority: 3 },
  { word: "attic", category: "Places", priority: 3 },
  { word: "backyard", category: "Places", priority: 1 },
  { word: "front yard", category: "Places", priority: 2 },
  { word: "garden", category: "Places", priority: 2 },
];

// School items
const SCHOOL: WordEntry[] = [
  { word: "book", category: "School", priority: 1 },
  { word: "pencil", category: "School", priority: 1 },
  { word: "pen", category: "School", priority: 1 },
  { word: "crayon", category: "School", priority: 1 },
  { word: "marker", category: "School", priority: 1 },
  { word: "paper", category: "School", priority: 1 },
  { word: "notebook", category: "School", priority: 2 },
  { word: "folder", category: "School", priority: 2 },
  { word: "eraser", category: "School", priority: 1 },
  { word: "ruler", category: "School", priority: 2 },
  { word: "scissors", category: "School", priority: 1 },
  { word: "glue", category: "School", priority: 1 },
  { word: "tape", category: "School", priority: 2 },
  { word: "stapler", category: "School", priority: 3 },
  { word: "backpack", category: "School", priority: 1 },
  { word: "desk", category: "School", priority: 1 },
  { word: "chair", category: "School", priority: 1 },
  { word: "table", category: "School", priority: 1 },
  { word: "chalkboard", category: "School", priority: 2 },
  { word: "whiteboard", category: "School", priority: 2 },
  { word: "computer", category: "School", priority: 1 },
  { word: "tablet", category: "School", priority: 1 },
  { word: "homework", category: "School", priority: 1 },
  { word: "test", category: "School", priority: 2 },
  { word: "project", category: "School", priority: 2 },
  { word: "art", category: "School", priority: 1 },
  { word: "music", category: "School", priority: 1 },
  { word: "math", category: "School", priority: 1 },
  { word: "reading", category: "School", priority: 1 },
  { word: "writing", category: "School", priority: 1 },
  { word: "science", category: "School", priority: 2 },
  { word: "gym", category: "School", priority: 1 },
  { word: "recess", category: "School", priority: 1 },
  { word: "lunch", category: "School", priority: 1 },
  { word: "snack", category: "School", priority: 1 },
  { word: "alphabet", category: "School", priority: 2 },
  { word: "letter", category: "School", priority: 1 },
  { word: "number", category: "School", priority: 1 },
  { word: "word", category: "School", priority: 1 },
  { word: "sentence", category: "School", priority: 2 },
  { word: "story", category: "School", priority: 1 },
  { word: "picture", category: "School", priority: 1 },
  { word: "drawing", category: "School", priority: 2 },
  { word: "painting", category: "School", priority: 2 },
  { word: "craft", category: "School", priority: 2 },
  { word: "calendar", category: "School", priority: 2 },
  { word: "clock", category: "School", priority: 1 },
  { word: "globe", category: "School", priority: 3 },
  { word: "map", category: "School", priority: 2 },
  { word: "locker", category: "School", priority: 3 },
  { word: "cafeteria", category: "School", priority: 2 },
  { word: "bus", category: "School", priority: 1 },
  { word: "school bus", category: "School", priority: 1 },
];

// Toys and play
const TOYS: WordEntry[] = [
  { word: "toy", category: "Toys", priority: 1 },
  { word: "ball", category: "Toys", priority: 1 },
  { word: "doll", category: "Toys", priority: 1 },
  { word: "teddy bear", category: "Toys", priority: 1 },
  { word: "stuffed animal", category: "Toys", priority: 1 },
  { word: "blocks", category: "Toys", priority: 1 },
  { word: "lego", category: "Toys", priority: 1 },
  { word: "puzzle", category: "Toys", priority: 1 },
  { word: "game", category: "Toys", priority: 1 },
  { word: "board game", category: "Toys", priority: 2 },
  { word: "video game", category: "Toys", priority: 1 },
  { word: "toy car", category: "Toys", priority: 1 },
  { word: "train", category: "Toys", priority: 1 },
  { word: "truck", category: "Toys", priority: 1 },
  { word: "airplane", category: "Toys", priority: 1 },
  { word: "helicopter", category: "Toys", priority: 2 },
  { word: "boat", category: "Toys", priority: 1 },
  { word: "robot", category: "Toys", priority: 1 },
  { word: "action figure", category: "Toys", priority: 2 },
  { word: "superhero", category: "Toys", priority: 2 },
  { word: "princess", category: "Toys", priority: 1 },
  { word: "unicorn", category: "Toys", priority: 1 },
  { word: "dragon", category: "Toys", priority: 2 },
  { word: "castle", category: "Toys", priority: 2 },
  { word: "playdough", category: "Toys", priority: 1 },
  { word: "clay", category: "Toys", priority: 2 },
  { word: "paint", category: "Toys", priority: 1 },
  { word: "bubbles", category: "Toys", priority: 1 },
  { word: "balloon", category: "Toys", priority: 1 },
  { word: "kite", category: "Toys", priority: 1 },
  { word: "jump rope", category: "Toys", priority: 2 },
  { word: "hula hoop", category: "Toys", priority: 2 },
  { word: "frisbee", category: "Toys", priority: 2 },
  { word: "bike", category: "Toys", priority: 1 },
  { word: "bicycle", category: "Toys", priority: 2 },
  { word: "scooter", category: "Toys", priority: 1 },
  { word: "skateboard", category: "Toys", priority: 2 },
  { word: "roller skates", category: "Toys", priority: 3 },
  { word: "tricycle", category: "Toys", priority: 2 },
  { word: "wagon", category: "Toys", priority: 2 },
  { word: "swing", category: "Toys", priority: 1 },
  { word: "slide", category: "Toys", priority: 1 },
  { word: "sandbox", category: "Toys", priority: 2 },
  { word: "trampoline", category: "Toys", priority: 2 },
  { word: "seesaw", category: "Toys", priority: 3 },
  { word: "playhouse", category: "Toys", priority: 2 },
  { word: "fort", category: "Toys", priority: 3 },
  { word: "tent", category: "Toys", priority: 2 },
  { word: "sticker", category: "Toys", priority: 1 },
  { word: "coloring book", category: "Toys", priority: 1 },
  { word: "puppet", category: "Toys", priority: 2 },
];

// Body parts
const BODY: WordEntry[] = [
  { word: "head", category: "Body", priority: 1 },
  { word: "hair", category: "Body", priority: 1 },
  { word: "face", category: "Body", priority: 1 },
  { word: "eye", category: "Body", priority: 1 },
  { word: "eyes", category: "Body", priority: 1 },
  { word: "nose", category: "Body", priority: 1 },
  { word: "mouth", category: "Body", priority: 1 },
  { word: "ear", category: "Body", priority: 1 },
  { word: "ears", category: "Body", priority: 1 },
  { word: "teeth", category: "Body", priority: 1 },
  { word: "tooth", category: "Body", priority: 2 },
  { word: "tongue", category: "Body", priority: 2 },
  { word: "chin", category: "Body", priority: 3 },
  { word: "cheek", category: "Body", priority: 3 },
  { word: "forehead", category: "Body", priority: 3 },
  { word: "neck", category: "Body", priority: 2 },
  { word: "shoulder", category: "Body", priority: 2 },
  { word: "arm", category: "Body", priority: 1 },
  { word: "elbow", category: "Body", priority: 2 },
  { word: "wrist", category: "Body", priority: 3 },
  { word: "hand", category: "Body", priority: 1 },
  { word: "finger", category: "Body", priority: 1 },
  { word: "thumb", category: "Body", priority: 2 },
  { word: "nail", category: "Body", priority: 3 },
  { word: "back", category: "Body", priority: 2 },
  { word: "chest", category: "Body", priority: 3 },
  { word: "tummy", category: "Body", priority: 1 },
  { word: "stomach", category: "Body", priority: 2 },
  { word: "belly button", category: "Body", priority: 2 },
  { word: "hip", category: "Body", priority: 3 },
  { word: "bottom", category: "Body", priority: 2 },
  { word: "leg", category: "Body", priority: 1 },
  { word: "knee", category: "Body", priority: 1 },
  { word: "ankle", category: "Body", priority: 2 },
  { word: "foot", category: "Body", priority: 1 },
  { word: "feet", category: "Body", priority: 1 },
  { word: "toe", category: "Body", priority: 1 },
  { word: "heel", category: "Body", priority: 3 },
  { word: "heart", category: "Body", priority: 1 },
  { word: "brain", category: "Body", priority: 2 },
  { word: "bone", category: "Body", priority: 2 },
  { word: "muscle", category: "Body", priority: 3 },
  { word: "skin", category: "Body", priority: 2 },
  { word: "blood", category: "Body", priority: 3 },
];

// Clothing
const CLOTHING: WordEntry[] = [
  { word: "shirt", category: "Clothing", priority: 1 },
  { word: "t-shirt", category: "Clothing", priority: 2 },
  { word: "pants", category: "Clothing", priority: 1 },
  { word: "jeans", category: "Clothing", priority: 2 },
  { word: "shorts", category: "Clothing", priority: 1 },
  { word: "dress", category: "Clothing", priority: 1 },
  { word: "skirt", category: "Clothing", priority: 2 },
  { word: "sweater", category: "Clothing", priority: 1 },
  { word: "jacket", category: "Clothing", priority: 1 },
  { word: "coat", category: "Clothing", priority: 1 },
  { word: "hoodie", category: "Clothing", priority: 2 },
  { word: "pajamas", category: "Clothing", priority: 1 },
  { word: "underwear", category: "Clothing", priority: 1 },
  { word: "socks", category: "Clothing", priority: 1 },
  { word: "shoes", category: "Clothing", priority: 1 },
  { word: "sneakers", category: "Clothing", priority: 2 },
  { word: "boots", category: "Clothing", priority: 1 },
  { word: "sandals", category: "Clothing", priority: 2 },
  { word: "slippers", category: "Clothing", priority: 2 },
  { word: "hat", category: "Clothing", priority: 1 },
  { word: "cap", category: "Clothing", priority: 2 },
  { word: "gloves", category: "Clothing", priority: 1 },
  { word: "mittens", category: "Clothing", priority: 2 },
  { word: "scarf", category: "Clothing", priority: 2 },
  { word: "belt", category: "Clothing", priority: 2 },
  { word: "tie", category: "Clothing", priority: 3 },
  { word: "glasses", category: "Clothing", priority: 1 },
  { word: "sunglasses", category: "Clothing", priority: 2 },
  { word: "watch", category: "Clothing", priority: 2 },
  { word: "swimsuit", category: "Clothing", priority: 2 },
  { word: "bathing suit", category: "Clothing", priority: 2 },
  { word: "rain boots", category: "Clothing", priority: 3 },
  { word: "raincoat", category: "Clothing", priority: 2 },
  { word: "umbrella", category: "Clothing", priority: 1 },
  { word: "uniform", category: "Clothing", priority: 3 },
  { word: "costume", category: "Clothing", priority: 2 },
  { word: "diaper", category: "Clothing", priority: 2 },
];

// Transportation
const TRANSPORTATION: WordEntry[] = [
  { word: "car", category: "Transportation", priority: 1 },
  { word: "bus", category: "Transportation", priority: 1 },
  { word: "truck", category: "Transportation", priority: 1 },
  { word: "van", category: "Transportation", priority: 2 },
  { word: "taxi", category: "Transportation", priority: 2 },
  { word: "ambulance", category: "Transportation", priority: 2 },
  { word: "fire truck", category: "Transportation", priority: 1 },
  { word: "police car", category: "Transportation", priority: 2 },
  { word: "train", category: "Transportation", priority: 1 },
  { word: "subway", category: "Transportation", priority: 3 },
  { word: "airplane", category: "Transportation", priority: 1 },
  { word: "helicopter", category: "Transportation", priority: 2 },
  { word: "boat", category: "Transportation", priority: 1 },
  { word: "ship", category: "Transportation", priority: 2 },
  { word: "motorcycle", category: "Transportation", priority: 2 },
  { word: "bicycle", category: "Transportation", priority: 1 },
  { word: "scooter", category: "Transportation", priority: 2 },
  { word: "skateboard", category: "Transportation", priority: 2 },
  { word: "stroller", category: "Transportation", priority: 2 },
  { word: "wheelchair", category: "Transportation", priority: 2 },
  { word: "rocket", category: "Transportation", priority: 2 },
  { word: "spaceship", category: "Transportation", priority: 2 },
  { word: "tractor", category: "Transportation", priority: 2 },
  { word: "garbage truck", category: "Transportation", priority: 2 },
  { word: "construction truck", category: "Transportation", priority: 3 },
  { word: "dump truck", category: "Transportation", priority: 3 },
  { word: "cement mixer", category: "Transportation", priority: 3 },
  { word: "crane", category: "Transportation", priority: 3 },
  { word: "bulldozer", category: "Transportation", priority: 3 },
  { word: "ice cream truck", category: "Transportation", priority: 2 },
];

// Weather and nature
const WEATHER: WordEntry[] = [
  { word: "sun", category: "Weather", priority: 1 },
  { word: "sunny", category: "Weather", priority: 1 },
  { word: "cloud", category: "Weather", priority: 1 },
  { word: "cloudy", category: "Weather", priority: 1 },
  { word: "rain", category: "Weather", priority: 1 },
  { word: "rainy", category: "Weather", priority: 1 },
  { word: "snow", category: "Weather", priority: 1 },
  { word: "snowy", category: "Weather", priority: 1 },
  { word: "wind", category: "Weather", priority: 1 },
  { word: "windy", category: "Weather", priority: 1 },
  { word: "storm", category: "Weather", priority: 2 },
  { word: "thunder", category: "Weather", priority: 2 },
  { word: "lightning", category: "Weather", priority: 2 },
  { word: "rainbow", category: "Weather", priority: 1 },
  { word: "fog", category: "Weather", priority: 3 },
  { word: "ice", category: "Weather", priority: 2 },
  { word: "hot", category: "Weather", priority: 1 },
  { word: "cold", category: "Weather", priority: 1 },
  { word: "warm", category: "Weather", priority: 1 },
  { word: "cool", category: "Weather", priority: 2 },
  { word: "temperature", category: "Weather", priority: 3 },
  { word: "weather", category: "Weather", priority: 1 },
  // Nature
  { word: "tree", category: "Weather", priority: 1 },
  { word: "flower", category: "Weather", priority: 1 },
  { word: "grass", category: "Weather", priority: 1 },
  { word: "leaf", category: "Weather", priority: 1 },
  { word: "plant", category: "Weather", priority: 1 },
  { word: "seed", category: "Weather", priority: 2 },
  { word: "rock", category: "Weather", priority: 1 },
  { word: "stone", category: "Weather", priority: 2 },
  { word: "dirt", category: "Weather", priority: 2 },
  { word: "mud", category: "Weather", priority: 2 },
  { word: "sand", category: "Weather", priority: 1 },
  { word: "water", category: "Weather", priority: 1 },
  { word: "sky", category: "Weather", priority: 1 },
  { word: "moon", category: "Weather", priority: 1 },
  { word: "star", category: "Weather", priority: 1 },
  { word: "night", category: "Weather", priority: 1 },
  { word: "day", category: "Weather", priority: 1 },
];

// Colors
const COLORS: WordEntry[] = [
  { word: "red", category: "Colors", priority: 1 },
  { word: "blue", category: "Colors", priority: 1 },
  { word: "yellow", category: "Colors", priority: 1 },
  { word: "green", category: "Colors", priority: 1 },
  { word: "orange", category: "Colors", priority: 1 },
  { word: "purple", category: "Colors", priority: 1 },
  { word: "pink", category: "Colors", priority: 1 },
  { word: "brown", category: "Colors", priority: 1 },
  { word: "black", category: "Colors", priority: 1 },
  { word: "white", category: "Colors", priority: 1 },
  { word: "gray", category: "Colors", priority: 1 },
  { word: "gold", category: "Colors", priority: 2 },
  { word: "silver", category: "Colors", priority: 2 },
  { word: "light", category: "Colors", priority: 1 },
  { word: "dark", category: "Colors", priority: 1 },
];

// Numbers and time
const NUMBERS_TIME: WordEntry[] = [
  { word: "one", category: "Numbers", priority: 1 },
  { word: "two", category: "Numbers", priority: 1 },
  { word: "three", category: "Numbers", priority: 1 },
  { word: "four", category: "Numbers", priority: 1 },
  { word: "five", category: "Numbers", priority: 1 },
  { word: "six", category: "Numbers", priority: 1 },
  { word: "seven", category: "Numbers", priority: 1 },
  { word: "eight", category: "Numbers", priority: 1 },
  { word: "nine", category: "Numbers", priority: 1 },
  { word: "ten", category: "Numbers", priority: 1 },
  { word: "zero", category: "Numbers", priority: 1 },
  { word: "first", category: "Numbers", priority: 2 },
  { word: "second", category: "Numbers", priority: 2 },
  { word: "third", category: "Numbers", priority: 2 },
  { word: "last", category: "Numbers", priority: 2 },
  { word: "next", category: "Numbers", priority: 2 },
  // Time
  { word: "morning", category: "Time", priority: 1 },
  { word: "afternoon", category: "Time", priority: 1 },
  { word: "evening", category: "Time", priority: 2 },
  { word: "night", category: "Time", priority: 1 },
  { word: "today", category: "Time", priority: 1 },
  { word: "tomorrow", category: "Time", priority: 1 },
  { word: "yesterday", category: "Time", priority: 1 },
  { word: "now", category: "Time", priority: 1 },
  { word: "later", category: "Time", priority: 1 },
  { word: "soon", category: "Time", priority: 2 },
  { word: "before", category: "Time", priority: 2 },
  { word: "after", category: "Time", priority: 2 },
  { word: "always", category: "Time", priority: 2 },
  { word: "never", category: "Time", priority: 2 },
  { word: "sometimes", category: "Time", priority: 2 },
  { word: "minute", category: "Time", priority: 2 },
  { word: "hour", category: "Time", priority: 2 },
  { word: "day", category: "Time", priority: 1 },
  { word: "week", category: "Time", priority: 1 },
  { word: "month", category: "Time", priority: 2 },
  { word: "year", category: "Time", priority: 2 },
  { word: "birthday", category: "Time", priority: 1 },
  { word: "holiday", category: "Time", priority: 2 },
  { word: "weekend", category: "Time", priority: 2 },
  // Days
  { word: "Monday", category: "Time", priority: 2 },
  { word: "Tuesday", category: "Time", priority: 2 },
  { word: "Wednesday", category: "Time", priority: 2 },
  { word: "Thursday", category: "Time", priority: 2 },
  { word: "Friday", category: "Time", priority: 2 },
  { word: "Saturday", category: "Time", priority: 2 },
  { word: "Sunday", category: "Time", priority: 2 },
];

// Basic responses and communication
const RESPONSES: WordEntry[] = [
  { word: "yes", category: "Responses", priority: 1 },
  { word: "no", category: "Responses", priority: 1 },
  { word: "please", category: "Responses", priority: 1 },
  { word: "thank you", category: "Responses", priority: 1 },
  { word: "thanks", category: "Responses", priority: 1 },
  { word: "sorry", category: "Responses", priority: 1 },
  { word: "excuse me", category: "Responses", priority: 2 },
  { word: "hello", category: "Responses", priority: 1 },
  { word: "hi", category: "Responses", priority: 1 },
  { word: "goodbye", category: "Responses", priority: 1 },
  { word: "bye", category: "Responses", priority: 1 },
  { word: "good morning", category: "Responses", priority: 1 },
  { word: "good night", category: "Responses", priority: 1 },
  { word: "more", category: "Responses", priority: 1 },
  { word: "all done", category: "Responses", priority: 1 },
  { word: "finished", category: "Responses", priority: 1 },
  { word: "help", category: "Responses", priority: 1 },
  { word: "I want", category: "Responses", priority: 1 },
  { word: "I need", category: "Responses", priority: 1 },
  { word: "I like", category: "Responses", priority: 1 },
  { word: "I don't like", category: "Responses", priority: 1 },
  { word: "I feel", category: "Responses", priority: 1 },
  { word: "what", category: "Responses", priority: 1 },
  { word: "where", category: "Responses", priority: 1 },
  { word: "when", category: "Responses", priority: 1 },
  { word: "who", category: "Responses", priority: 1 },
  { word: "why", category: "Responses", priority: 1 },
  { word: "how", category: "Responses", priority: 1 },
  { word: "which", category: "Responses", priority: 2 },
  { word: "wait", category: "Responses", priority: 1 },
  { word: "stop", category: "Responses", priority: 1 },
  { word: "go", category: "Responses", priority: 1 },
  { word: "come", category: "Responses", priority: 1 },
  { word: "look", category: "Responses", priority: 1 },
  { word: "listen", category: "Responses", priority: 1 },
  { word: "again", category: "Responses", priority: 1 },
  { word: "different", category: "Responses", priority: 2 },
  { word: "same", category: "Responses", priority: 2 },
  { word: "turn", category: "Responses", priority: 2 },
  { word: "my turn", category: "Responses", priority: 1 },
  { word: "your turn", category: "Responses", priority: 1 },
];

// Positions and directions
const POSITIONS: WordEntry[] = [
  { word: "up", category: "Positions", priority: 1 },
  { word: "down", category: "Positions", priority: 1 },
  { word: "in", category: "Positions", priority: 1 },
  { word: "out", category: "Positions", priority: 1 },
  { word: "on", category: "Positions", priority: 1 },
  { word: "off", category: "Positions", priority: 1 },
  { word: "over", category: "Positions", priority: 1 },
  { word: "under", category: "Positions", priority: 1 },
  { word: "above", category: "Positions", priority: 2 },
  { word: "below", category: "Positions", priority: 2 },
  { word: "inside", category: "Positions", priority: 1 },
  { word: "outside", category: "Positions", priority: 1 },
  { word: "here", category: "Positions", priority: 1 },
  { word: "there", category: "Positions", priority: 1 },
  { word: "left", category: "Positions", priority: 1 },
  { word: "right", category: "Positions", priority: 1 },
  { word: "front", category: "Positions", priority: 1 },
  { word: "back", category: "Positions", priority: 1 },
  { word: "top", category: "Positions", priority: 1 },
  { word: "bottom", category: "Positions", priority: 1 },
  { word: "middle", category: "Positions", priority: 1 },
  { word: "side", category: "Positions", priority: 2 },
  { word: "corner", category: "Positions", priority: 2 },
  { word: "between", category: "Positions", priority: 2 },
  { word: "next to", category: "Positions", priority: 2 },
  { word: "near", category: "Positions", priority: 2 },
  { word: "far", category: "Positions", priority: 2 },
  { word: "close", category: "Positions", priority: 2 },
  { word: "away", category: "Positions", priority: 2 },
  { word: "around", category: "Positions", priority: 2 },
  { word: "through", category: "Positions", priority: 2 },
  { word: "across", category: "Positions", priority: 2 },
  { word: "forward", category: "Positions", priority: 2 },
  { word: "backward", category: "Positions", priority: 2 },
];

// Descriptive words
const DESCRIPTIVE: WordEntry[] = [
  { word: "big", category: "Descriptive", priority: 1 },
  { word: "small", category: "Descriptive", priority: 1 },
  { word: "little", category: "Descriptive", priority: 1 },
  { word: "large", category: "Descriptive", priority: 2 },
  { word: "tiny", category: "Descriptive", priority: 2 },
  { word: "huge", category: "Descriptive", priority: 2 },
  { word: "tall", category: "Descriptive", priority: 1 },
  { word: "short", category: "Descriptive", priority: 1 },
  { word: "long", category: "Descriptive", priority: 1 },
  { word: "wide", category: "Descriptive", priority: 2 },
  { word: "fat", category: "Descriptive", priority: 2 },
  { word: "thin", category: "Descriptive", priority: 2 },
  { word: "fast", category: "Descriptive", priority: 1 },
  { word: "slow", category: "Descriptive", priority: 1 },
  { word: "quick", category: "Descriptive", priority: 2 },
  { word: "heavy", category: "Descriptive", priority: 2 },
  { word: "light", category: "Descriptive", priority: 2 },
  { word: "hard", category: "Descriptive", priority: 1 },
  { word: "soft", category: "Descriptive", priority: 1 },
  { word: "smooth", category: "Descriptive", priority: 2 },
  { word: "rough", category: "Descriptive", priority: 2 },
  { word: "wet", category: "Descriptive", priority: 1 },
  { word: "dry", category: "Descriptive", priority: 1 },
  { word: "clean", category: "Descriptive", priority: 1 },
  { word: "dirty", category: "Descriptive", priority: 1 },
  { word: "new", category: "Descriptive", priority: 1 },
  { word: "old", category: "Descriptive", priority: 1 },
  { word: "young", category: "Descriptive", priority: 2 },
  { word: "full", category: "Descriptive", priority: 1 },
  { word: "empty", category: "Descriptive", priority: 1 },
  { word: "open", category: "Descriptive", priority: 1 },
  { word: "closed", category: "Descriptive", priority: 1 },
  { word: "loud", category: "Descriptive", priority: 1 },
  { word: "quiet", category: "Descriptive", priority: 1 },
  { word: "noisy", category: "Descriptive", priority: 2 },
  { word: "bright", category: "Descriptive", priority: 2 },
  { word: "dark", category: "Descriptive", priority: 1 },
  { word: "pretty", category: "Descriptive", priority: 1 },
  { word: "beautiful", category: "Descriptive", priority: 2 },
  { word: "ugly", category: "Descriptive", priority: 2 },
  { word: "cute", category: "Descriptive", priority: 1 },
  { word: "nice", category: "Descriptive", priority: 1 },
  { word: "yucky", category: "Descriptive", priority: 1 },
  { word: "yummy", category: "Descriptive", priority: 1 },
  { word: "delicious", category: "Descriptive", priority: 2 },
  { word: "sweet", category: "Descriptive", priority: 1 },
  { word: "sour", category: "Descriptive", priority: 2 },
  { word: "salty", category: "Descriptive", priority: 2 },
  { word: "spicy", category: "Descriptive", priority: 2 },
  { word: "bitter", category: "Descriptive", priority: 3 },
  { word: "sharp", category: "Descriptive", priority: 2 },
  { word: "dull", category: "Descriptive", priority: 3 },
  { word: "round", category: "Descriptive", priority: 1 },
  { word: "square", category: "Descriptive", priority: 1 },
  { word: "flat", category: "Descriptive", priority: 2 },
  { word: "straight", category: "Descriptive", priority: 2 },
  { word: "crooked", category: "Descriptive", priority: 3 },
  { word: "broken", category: "Descriptive", priority: 1 },
  { word: "fixed", category: "Descriptive", priority: 2 },
  { word: "safe", category: "Descriptive", priority: 1 },
  { word: "dangerous", category: "Descriptive", priority: 2 },
  { word: "easy", category: "Descriptive", priority: 1 },
  { word: "difficult", category: "Descriptive", priority: 2 },
  { word: "same", category: "Descriptive", priority: 1 },
  { word: "different", category: "Descriptive", priority: 1 },
  { word: "special", category: "Descriptive", priority: 1 },
  { word: "favorite", category: "Descriptive", priority: 1 },
  { word: "best", category: "Descriptive", priority: 1 },
  { word: "worst", category: "Descriptive", priority: 2 },
  { word: "real", category: "Descriptive", priority: 2 },
  { word: "fake", category: "Descriptive", priority: 2 },
  { word: "true", category: "Descriptive", priority: 2 },
  { word: "right", category: "Descriptive", priority: 1 },
  { word: "wrong", category: "Descriptive", priority: 1 },
];

// Household items
const HOUSEHOLD: WordEntry[] = [
  { word: "bed", category: "Household", priority: 1 },
  { word: "pillow", category: "Household", priority: 1 },
  { word: "blanket", category: "Household", priority: 1 },
  { word: "sheet", category: "Household", priority: 2 },
  { word: "couch", category: "Household", priority: 1 },
  { word: "sofa", category: "Household", priority: 2 },
  { word: "chair", category: "Household", priority: 1 },
  { word: "table", category: "Household", priority: 1 },
  { word: "desk", category: "Household", priority: 1 },
  { word: "lamp", category: "Household", priority: 1 },
  { word: "light", category: "Household", priority: 1 },
  { word: "door", category: "Household", priority: 1 },
  { word: "window", category: "Household", priority: 1 },
  { word: "floor", category: "Household", priority: 1 },
  { word: "wall", category: "Household", priority: 2 },
  { word: "ceiling", category: "Household", priority: 3 },
  { word: "stairs", category: "Household", priority: 2 },
  { word: "rug", category: "Household", priority: 2 },
  { word: "carpet", category: "Household", priority: 3 },
  { word: "curtain", category: "Household", priority: 3 },
  { word: "mirror", category: "Household", priority: 2 },
  { word: "clock", category: "Household", priority: 1 },
  { word: "television", category: "Household", priority: 1 },
  { word: "TV", category: "Household", priority: 1 },
  { word: "remote", category: "Household", priority: 2 },
  { word: "phone", category: "Household", priority: 1 },
  { word: "computer", category: "Household", priority: 1 },
  { word: "refrigerator", category: "Household", priority: 2 },
  { word: "fridge", category: "Household", priority: 2 },
  { word: "stove", category: "Household", priority: 2 },
  { word: "oven", category: "Household", priority: 2 },
  { word: "microwave", category: "Household", priority: 2 },
  { word: "dishwasher", category: "Household", priority: 3 },
  { word: "sink", category: "Household", priority: 1 },
  { word: "toilet", category: "Household", priority: 1 },
  { word: "bathtub", category: "Household", priority: 1 },
  { word: "shower", category: "Household", priority: 1 },
  { word: "towel", category: "Household", priority: 1 },
  { word: "soap", category: "Household", priority: 1 },
  { word: "shampoo", category: "Household", priority: 2 },
  { word: "toothbrush", category: "Household", priority: 1 },
  { word: "toothpaste", category: "Household", priority: 1 },
  { word: "hairbrush", category: "Household", priority: 2 },
  { word: "comb", category: "Household", priority: 2 },
  { word: "plate", category: "Household", priority: 1 },
  { word: "bowl", category: "Household", priority: 1 },
  { word: "cup", category: "Household", priority: 1 },
  { word: "glass", category: "Household", priority: 1 },
  { word: "bottle", category: "Household", priority: 1 },
  { word: "fork", category: "Household", priority: 1 },
  { word: "spoon", category: "Household", priority: 1 },
  { word: "knife", category: "Household", priority: 1 },
  { word: "napkin", category: "Household", priority: 2 },
  { word: "pot", category: "Household", priority: 2 },
  { word: "pan", category: "Household", priority: 2 },
  { word: "trash", category: "Household", priority: 1 },
  { word: "garbage", category: "Household", priority: 2 },
  { word: "broom", category: "Household", priority: 2 },
  { word: "mop", category: "Household", priority: 3 },
  { word: "vacuum", category: "Household", priority: 3 },
  { word: "basket", category: "Household", priority: 2 },
  { word: "box", category: "Household", priority: 1 },
  { word: "bag", category: "Household", priority: 1 },
  { word: "key", category: "Household", priority: 1 },
  { word: "lock", category: "Household", priority: 2 },
  { word: "fan", category: "Household", priority: 2 },
  { word: "heater", category: "Household", priority: 3 },
  { word: "air conditioner", category: "Household", priority: 3 },
];

// Combine all categories
export const ALL_WORDS: WordEntry[] = [
  ...CORE_VERBS,
  ...EMOTIONS,
  ...PEOPLE,
  ...ANIMALS,
  ...FOODS,
  ...DRINKS,
  ...PLACES,
  ...SCHOOL,
  ...TOYS,
  ...BODY,
  ...CLOTHING,
  ...TRANSPORTATION,
  ...WEATHER,
  ...COLORS,
  ...NUMBERS_TIME,
  ...RESPONSES,
  ...POSITIONS,
  ...DESCRIPTIVE,
  ...HOUSEHOLD,
];

// Function to get unique words (no duplicates)
export function getUniqueWords(): WordEntry[] {
  const seen = new Set<string>();
  return ALL_WORDS.filter((entry) => {
    const key = entry.word.toLowerCase();
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}

// Function to get top N words by priority
export function getTopWords(count: number): WordEntry[] {
  const unique = getUniqueWords();
  return unique
    .sort((a, b) => a.priority - b.priority || a.word.localeCompare(b.word))
    .slice(0, count);
}

// Export word count for verification
export function getWordStats() {
  const unique = getUniqueWords();
  const byCategory: Record<string, number> = {};
  const byPriority: Record<number, number> = { 1: 0, 2: 0, 3: 0 };

  unique.forEach((entry) => {
    byCategory[entry.category] = (byCategory[entry.category] || 0) + 1;
    byPriority[entry.priority]++;
  });

  return {
    total: unique.length,
    byCategory,
    byPriority,
  };
}

// Main execution if run directly
if (require.main === module) {
  const stats = getWordStats();
  console.log("\n=== Word List Statistics ===\n");
  console.log(`Total unique words: ${stats.total}`);
  console.log("\nBy Priority:");
  console.log(`  Priority 1 (Core/Dolch): ${stats.byPriority[1]}`);
  console.log(`  Priority 2 (High): ${stats.byPriority[2]}`);
  console.log(`  Priority 3 (Medium): ${stats.byPriority[3]}`);
  console.log("\nBy Category:");
  Object.entries(stats.byCategory)
    .sort((a, b) => b[1] - a[1])
    .forEach(([cat, count]) => {
      console.log(`  ${cat}: ${count}`);
    });
}
